### ISSUE TITLE
Logs are not being printed

### ISSUE THREAD

**Issue by fortunac** [draperlaboratory/cbat_tools#106]
https://github.com/draperlaboratory/cbat_tools/blob/a626bfcedf24db3d675d575f54ce0a43ab31c5d6/wp/plugin/wp.ml#L155

is deprecated with warning message:

```
main.warning> The deprecated Bap.Std.Log.start function is used.
This function does nothing. Use `Bap_main.init' instead
```

However, according to the documentation, 
```
Attention: function is only needed when BAP framework is embedded in another
application. It shall not be called in BAP plugins. If you're not sure whether you need
to call it, then don't call it.
```

**Comment by ivg** [comment]
When you're writing a plugin, you shouldn't start the log service, as the host program will set the logging for you.

**Comment by fortunac** [comment]
Thanks Ivan! I was looking in the wrong directory for the log files. Is there also a way to have the logs printed to `stdout`?

**Comment by ivg** [comment]
You can use the `--log-dir` parameter or the `BAP_LOG_DIR` environment variable to specify the location of the log file, e.g., `bap . --log-dir=.` will create a log file in the current folder. 

While the `Bap_main.init` interface indeed allows specifying a formatter or channel as the looging output, the command line option itself is only accepting a directory. We can update the command line, and let it accept more options, including logging to stderr. 

But, I honestly, don't see any reason to redirect it to a channel. You can always open the `log` file in emacs and enable the `auto-revert-mode` (if it is not enabled by default, it is a good idea to always use it). If you're not using emacs, I believe that all modern text editors are able to reload files automatically on change.

**Comment by fortunac** [comment]
Thanks a bunch!
