### ISSUE TITLE
Update z3 to 4.8.8-1

### ISSUE THREAD

**Issue by philzook58** [draperlaboratory/cbat_tools#110]
The opam-repository could be updated so that installation becomes simpler. Also maybe we get more bug fixes.

**Comment by fortunac** [comment]
Updated instructions in READMEs for this in #152.

**Comment by ivg** [comment]
I would suggest using 4.8.8-1, see
* https://github.com/ocaml/opam-repository/pull/16535
* https://github.com/Z3Prover/z3/pull/4468

**Comment by fortunac** [comment]
This is great, Ivan! Thanks for the heads up.

**Comment by fortunac** [comment]
Closing as Z3 is installed by BAP now.
