### ISSUE TITLE
Add wp cli option to check for null dereferences

### ISSUE THREAD

**Issue by DieracDelta** [draperlaboratory/cbat_tools#124]
The wp library is capable of checking for null dereferences. It would be useful to add this as a command line flag option to the wp plugin, such that `"--wp-check-null-deref"` reports SAT and provides inputs that force the provided binary to perform the null dereference.  Simple examples include:
```c
int main(int argc,char ** argv) {
        *((int*)NULL);
        return 0;
}
```
and 
```c
int main(int argc,char ** argv) {
        if (argc == 3){
                *((int*)NULL);
        }
        return 0;
}
```
Similar to the `simple-wp` example, the expected output model for the latter test case would include `RDI=3`.

**Comment by fortunac** [comment]
Closed with #131.
