### ISSUE TITLE
Single program analyses with custom smtlib conditions require space character

### ISSUE THREAD

**Issue by DieracDelta** [draperlaboratory/cbat_tools#146]
In single program analyses, when including a custom pre or post condition, it seems that any references to `mem` must be followed by a space. This error in the case that `mem` or other custom variables used by CBAT are followed by a closing parenthese or newline.

[Here](https://github.com/draperlaboratory/CBAT-internal/tree/jrestivo/wp_examples/documentation/complex_examples/example_13_8bit) is a relevant example. To run, just run `bash run_wp.sh` with wp installed. The interesting bit is the [post condition](https://github.com/draperlaboratory/CBAT-internal/blob/jrestivo/wp_examples/documentation/complex_examples/example_13_8bit/post_cond.smt):

```
(declare-const x (_ BitVec 64))
(assert
 (bvule
  (select  mem 
	   (bvadd (bvsub init_RSP #x000000000000001c) x))
  (select  mem 
	   (bvadd (bvsub init_RSP #x000000000000001b) x))))
```

CBAT runs successfully.  However, I get an error that `mem` is not found when I remove the " " space character following `mem`: 

```
pass "wp" failed in runtime with Z3.Error("(error \"line 7 column 11: unknown constant mem\")\n")
```

Note that this is only a problem for single binary analysis. I believe the function that is causing the error is [here](https://github.com/draperlaboratory/cbat_tools/blob/master/wp/lib/bap_wp/src/z3_utils.ml#L63). The function `~f` in the fold is matching on the variable name used by Z3 (in this case, `mem`) with a space appended on after. If the variable is followed by a closing parenthese or other type of whitespace (for example newline or tab), this snippet of code won't match on the variable. This isn't an issue with comparisons between binaries as a different function is used and looks for a preceding `init_` or an appended `_mod` or `_orig`.

Note that when I remove the space from being concatenated on line 67, I no longer get an error and CBAT works as expected. E.g.

```
~pattern:(Var.name var)
```

However, this fix doesn't account for the case when a user creates a variable name that contains `Var.name` in a custom SMTLIB expression. Instead for single binaries, it might make sense to add in a relatively unique identifier like prepending "VAR" to all custom variables like `mem`, and mention in the user documentation that the user should not create new variables that start with `VAR`. I have no idea how hard this would be to implement. Alternatively, I can add in some documentation about this to the relevant README to warn users to include a space after referencing variables used internally by CBAT.

**Comment by fortunac** [comment]
Handled in #147.
