### ISSUE TITLE
specifying function name on per binary basis

### ISSUE THREAD

**Issue by DieracDelta** [draperlaboratory/cbat_tools#164]
Mangling (as seen in [this](https://github.com/draperlaboratory/CBAT-internal/tree/jrestivo/wp_examples/documentation/other_language_examples/ocaml_example) ocaml example) sometimes results in differing names between binaries. Perhaps we could add in a pair of flags to allow this sort of analysis in cbat. For example:

```
bap --pass=wp --wp-compare --wp-file1=main_1.bpj --wp-file2=main_2.bpj --wp-function1="main_1_foo" --wp-function2="main_2_foo"
```

Note that this does conflict with the `--wp-function` flag. Maybe we could keep this functionality (assume both function names are the same), but make this flag mutually exclusive with the `--wp-function1/--wp-function2` flags.

**Comment by fortunac** [comment]
Closed with #273.
