### ISSUE TITLE
Give names to VCCs

### ISSUE THREAD

**Issue by fortunac** [draperlaboratory/cbat_tools#17]
This is a little tricky because many VCs can be created for a given application, and it's not clear which one contributes to a SAT result.

One possibility is to add a bunch of dummy VCs of the form `vc_name = vc_body`, at each VC creation time, (where `vc_name` is some fresh boolean) and maintain the map of actual names to `vc_name`s.

Finally given a `SAT` result, we could check the assignments to see which one was refuted.

Note, we need to generate `(vc_name = vc_body) => vc_body` instead of just `vc_body` to get the intended result.

**Comment by codyroux** [comment]
Is this still open?

**Comment by fortunac** [comment]
I believe this was handled in d6b465194978d3e1e084d0893eef0875dc7929c3
