### ISSUE TITLE
Rework print flags

### ISSUE THREAD

**Issue by philzook58** [draperlaboratory/cbat_tools#202]
Currently you need both --wp-print-paths and --wp-show-refuted-goals to get paths to print. This is confusing.

**Comment by fortunac** [comment]
Related to #193.

**Comment by fortunac** [comment]
Possible options I'm thinking are:
- Combine all the options into a single flag, `--wp-show=bir,refuted-goals,paths`. We could have WP automatically print the refuted goals if we have paths as an option.
- A general `--wp-verbosity=level` flag. The higher the level, the more details we print out. Starting from `bir`, then `bir,refuted-goals`, and then `bir,refuted-goals,paths`.

Thoughts? Suggestions? Complaints?
