### ISSUE TITLE
Add hooks for valid memory accesses

### ISSUE THREAD

**Issue by codyroux** [draperlaboratory/cbat_tools#21]
For the most part, just create a Z3 predicate `Valid(n)` that takes a memory access, and asserts that it is a valid access.

The tough part is adding `Valid(k)` *assertions*, which typically result either from being at some reasonable offset from `SP`, or being part of an allocation, which would look something like

>if `malloc(n)` was called, then either the result is `0` or `forall k <= n, Valid(res + k)`

**Comment by philzook58** [comment]
This is also important for the gdb output. Currently it does produce values out of memory, but it ignores the default value and uses invalid memory locations for actual x86

**Comment by fortunac** [comment]
Closed with #260.
