### ISSUE TITLE
multiple models for unit tests

### ISSUE THREAD

**Issue by DieracDelta** [draperlaboratory/cbat_tools#225]
Currently in our tests, we assume that there is one correct model when invoking `test_plugin` in `test_wp.ml`. We should add a way to provide multiple models. This will allow us to more precisely test the correctness of tests that have multiple solutions, such as nqueens and sudoku. 

To do this, a simple approach would be to include a list of models of type `((string * string) list) list` as `~expected_regs` to `test_plugin` and propagate this down to `check_model`, where we would perform several iterations over the output (instead of one).

An example parameter for `expected_regs` would be:

```
~expected_regs:[[("RSI", "0x0000000000000010"); ("RCX", "0x0000000000000007")]; [("RSI", "0x0000000000000010"); ("RCX", "0x0000000000000008")];]
```

This would allow us to check that the model either matches `RSI = 0x10 and RCX = 0x7` or `RSI = 0x10 and RCX = 0x8`.

**Comment by fortunac** [comment]
Closed with #228.
