### ISSUE TITLE
Add functionality to run counter-models in gdb

### ISSUE THREAD

**Issue by codyroux** [draperlaboratory/cbat_tools#25]
We can generate GDB command files (https://sourceware.org/gdb/onlinedocs/gdb/Command-Files.html) to set breakpoints and register values to attempt to exercise concrete counter models of properties in a run-time environment.

With more work, we can extend this to memory values as well.

I don't expect this to be extraordinarily scalable, since the target function needs to be reached in the first place, and there are many constraints on valid memory values which we are not tracking, etc.

It'll be good for debugging and exploration though.

**Comment by fortunac** [comment]
Handled with #70, #72, and #89.
