### ISSUE TITLE
Update required dependencies

### ISSUE THREAD

**Issue by fortunac** [draperlaboratory/cbat_tools#256]
We need to update the list of dependencies WP uses and make sure they are listed in the correct places.
- Update site, opam file, and dune files from `oUnit` to `ounit2`
  - Change any instance of `open oUnit` to `open oUnit2`
- Add `re` to the opam and dune files

Files that need changed:
- `lib/bap_wp/bap_wp.opam`
- `lib/bap_wp/src/dune`
- `lib/bap_wp/tests/unit/dune`
- `lib/bap_wp/tests/performance/dune`

**Comment by fortunac** [comment]
- Include `Core` in the list of dependencies on the site/opam/dune files. (We currently only have `Core_kernel`.)

**Comment by jtpaasch** [comment]
Include `opam install .` and `opam remove .` in the relevant `lib/bap_wp/Makefile` build targets.

**Comment by fortunac** [comment]
Closed with #261
