### ISSUE TITLE
Create a way to handle brand new (valid) variables in smtlib2 strings. 

### ISSUE THREAD

**Issue by gltrost** [draperlaboratory/cbat_tools#296]
Right now, we can handle smtlib2 strings with variables like registers, memory, certain suffixes and prefixes, etc. However, we don't have a way to handle newly defined variables. For example, we maybe want to create a brand new variable `x` to create a stement like 

```
(assert (and (bvule x RDX) (= (select mem (bvadd x RSI)) (select mem (bvadd x RDI))))
``` 
Right now this just throws a `Z3.Error` since `x` isn't recognized. 

To address this issue, @codyroux recommended we try one of the following:
1. We allow wp to recognize all syntactically valid new-variable inputs. 
2. We create a flag that specifies all new variable names (like `--new-vars="x"`, for example). 
3. We create a fresh special prefix that the user can user and be assured creates a new, valid variable name (like `wp_fresh_x`, where `wp_fresh` is the special prefix).

Other ideas are welcomed.

**Comment by gltrost** [comment]
Each of the three mentioned ideas for handling this issue have drawbacks:
(1) can lead to typos being turned into new fresh variables without the user intending it. For example, writing `rax` when you meant to write `RAX` would now result in a new variable called `rax`. 
(2) is a little heavy, and requires the user to include a new flag every time they need to add a new variable. 
(3) would require the user to have to remember the special new variable prefix every time they need to make a new smtlib statement. 

Of the three options though, I think (3) is the best and has the fewest drawbacks.

**Comment by gltrost** [comment]
One other thing to consider is how to specify the type of the new variables we create. _As far as I've looked into it, it looks like we need to declare a type when we create a variable_, though if anyone knows more, please tell.

We can make this anywhere as complicated as infering the type that the user inputs, to as simple as having the user specify what type they want a variable to be. 

If we go with the latter, then some ideas for working this into the implementation are: 
(A) If we use a flag, just allow the user to specify the type along with the name of the variable. For example `--new-vars="x:reg64_t`.
(B) If we use a variable prefix, we can add the type to the name of the variable. For example `(assert (= RAX wp-fresh-reg64_t-x))`. 

Neither of these ideas are very elegant or simple, so I'm open to other ideas.

**Comment by codyroux** [comment]
apparently you can declare variables right into the smt-lib string you're passing, e.g. `'(declare-const x Int) (assert (= RAX x))` (thanks @philzook58 )

**Comment by codyroux** [comment]
@gltrost is this resolved?

**Comment by gltrost** [comment]
> @gltrost is this resolved?

Yes. At least in practice this is no longer an issue, since we can declare new variables as either `forall ((x sort))` or `declare-const x sort`.
