### ISSUE TITLE
Integrate Runner module into master branch

### ISSUE THREAD

**Issue by codyroux** [draperlaboratory/cbat_tools#317]
Currently it is quite finicky to invoke WP as a library, as the setup involved is finicky and quite a bit of work is needed to create all of the enviroment components.

Conversely, there is quite a bit of code in the plugin side, which does exactly this set up. There is no real need for this to be on the plugin side, only a few data from the plugin infrastructure are used.

This is remedied in the `demo-invocation` branch (https://github.com/draperlaboratory/cbat_tools/tree/demo-invocation) but the implementation is messy and needs to be cleaned up and tested.

**Comment by fortunac** [comment]
Fixed in #319.
