### ISSUE TITLE
Add preconditions which bound possible values of RSP

### ISSUE THREAD

**Issue by codyroux** [draperlaboratory/cbat_tools#33]
This is very X86/X86_64 specific, but I think it's a good idea to have some lower bounds on possible values of `RSP`, just for sanity's sake, say `0xFFFFFFFF00000000 <= RSP <= 0xFFFFFFFFFFFFFFFF - 0x400`.

Not sure it'll help all that much, but it'll be reassuring to have a bit more realistic stack values.

**Comment by fortunac** [comment]
Handled in #107
