### ISSUE TITLE
Determining value of a memory comparing while looking for a refuted goal

### ISSUE THREAD

**Issue by fortunac** [draperlaboratory/cbat_tools#59]
In the case of a memory comparison while we are looking for a refuted goal
```
| Goal g ->
  let goal_val = Expr.substitute g.goal_val olds news in
  let goal_res = Option.value_exn (Z3.Model.eval model goal_val true) in
  if Bool.is_false goal_res then
  ...
```
is unable to determine when a memory comparison is false.

Running `Bool.get_bool_value goal_res` results in `L_UNDEF`.

**Comment by codyroux** [comment]
Solved, with PR #61
