### ISSUE TITLE
Inconsistent behavior in WP function unfolding

### ISSUE THREAD

**Issue by codyroux** [draperlaboratory/cbat_tools#67]
Right now, calling

> bap foo --pass=wp --wp-inline=true

inlines *nothing*, since the `wp-inline-funcs` flag is not set and defaults to the empty list.

Similarly,

> bap foo --pass=wp --wp-inline-funcs=foo

does not inline `foo` since the `wp-inline` flag is not set!

My feeling is that not specifying a `wp-inline-funcs` inlines *everything* rather than nothing, and that `wp-inline-funcs` should imply `wp-inline`.

**Comment by fortunac** [comment]
Setting `wp-file1` and `wp-file2` should also imply `wp-compare`.

**Comment by fortunac** [comment]
Handled in #73
