### ISSUE TITLE
Preserving names of registers 

### ISSUE THREAD

**Issue by fortunac** [draperlaboratory/cbat_tools#74]
In `strip_final_digits`:

https://github.com/draperlaboratory/cbat_tools/blob/7a8d7c6c42b9b0011fdbb38008c769655ec1e1f5/wp/lib/bap_wp/src/output.ml#L60

We are also stripping out the 8-12 from registers r8 - r12, and as a result we are setting a nonexistent registers, i.e.:

```
set $r = 0
```

**Comment by philzook58** [comment]
The commit above seems to have addressed this issue
