### ISSUE TITLE
Print concrete addresses along with paths

### ISSUE THREAD

**Issue by codyroux** [draperlaboratory/cbat_tools#75]
Right now https://github.com/draperlaboratory/cbat_tools/blob/7a8d7c6c42b9b0011fdbb38008c769655ec1e1f5/wp/lib/bap_wp/src/constraint.mli#L100 gets the refuted goals and paths to it as a path object.

Path objects are just  maps from `tid`s to `bools` (branches and the paths they take), which are useful, but hard to read in an output. As a result, `Constr.print_refuted_goals` and `Constr.refuted_goal_to_string` discard the path.

However, when stepping trough the counter-example with gdb, it's useful to be able to assess whether we're going down the right path with regards to the counter-model, so having a `Constr.refuted_goal_path_to_string` would be nice.

This function should include the *concrete* addresses of the branch, which Ivan tells me can be obtained using `Term.get_attr address t`. Unfortunately this means tracking terms in addition to their `tid`s, or look up the terms each time using `Term.find` on the whole subroutine.

**Comment by fortunac** [comment]
Handled in #81
