### ISSUE TITLE
Add CBAT logo to README.

### ISSUE THREAD

**Issue by codyroux** [draperlaboratory/cbat_tools#79]
Self explanatory.

**Comment by dbeigi** [comment]
Hi @codyroux i'll try and add a logo

**Comment by dbeigi** [comment]
@codyroux Let me know what you think of it

**Comment by codyroux** [comment]
Hi @dbeigi, I like the PR, but I'm not sure I'd call the change a logo _per se_. I'll approve the PR with changes to the commit message though.

Best,
Cody
